
#ifndef __REGISTER_MAP_H__
#define __REGISTER_MAP_H__

#define PERIPH_BASE         (0x40000000UL)
#define CORE_PERIPPH_BASE   (0xE000E00UL)

#define SYSTICK_OFFSET       (0x10)
#define SYSTICK_BASE  (CORE_PERIPPH_BASE+SYSTICK_OFFSET)

#define GPIO_A_OFFSET   (0x10800UL)
#define GPIO_A_BASE    (PERIPH_BASE+GPIO_A_OFFSET)

#define GPIO_B_OFFSET   (0x10C00UL)
#define GPIO_B_BASE    (PERIPH_BASE+GPIO_B_OFFSET)

#define GPIO_C_OFFSET   (0x11000UL)
#define GPIO_C_BASE     (PERIPH_BASE+GPIO_C_OFFSET)

#define GPIO_D_OFFSET    (0x11400UL)
#define GPIO_D_BASE     (PERIPH_BASE+GPIO_D_OFFSET)

#define RCC_OFFSET           (0x21000UL)
#define RCC_BASE        (PERIPH_BASE+RCC_OFFSET)

#define ADC1_OFFSET       (0x127FFUL)
#define ADC1_BASE        (PERIPH_BASE+ADC1_OFFSET)

#define ADC2_OFFSET       (0x12BFFUL)
#define ADC2_BASE        (PERIPH_BASE+ADC2_OFFSET)

#endif
